In [17]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
#!pip install mlxtend

In [2]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

In [3]:
#items = []
#with open("toy_dataset.csv") as f:
#    items = f.read()

In [18]:
items = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [5]:
items

[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
 ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
 ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [7]:
# splitting the data into separate transactions using separator as "\n"
#items = items.split("\n")
#items_list = []
#for i in items:
#    items_list.append(i.split(","))

In [8]:
items_list=items

In [ ]:
#items_list

In [19]:
te = TransactionEncoder()
te_ary = te.fit(items_list).transform(items_list)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [11]:
#apriori(df, min_support=0.4, use_colnames=True)

In [13]:
frequent_itemsets = apriori(df, min_support=0.3, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

    support                                     itemsets  length
0       0.4                                       (Corn)       1
1       0.8                                       (Eggs)       1
2       1.0                               (Kidney Beans)       1
3       0.6                                       (Milk)       1
4       0.4                                     (Nutmeg)       1
5       0.6                                      (Onion)       1
6       0.6                                     (Yogurt)       1
7       0.4                         (Corn, Kidney Beans)       2
8       0.8                         (Eggs, Kidney Beans)       2
9       0.4                                 (Eggs, Milk)       2
10      0.4                               (Eggs, Nutmeg)       2
11      0.6                                (Eggs, Onion)       2
12      0.4                               (Eggs, Yogurt)       2
13      0.6                         (Milk, Kidney Beans)       2
14      0.4                       (Nutmeg, Kidney Beans)       2
15      0.6                        (Onion, Kidney Beans)       2
16      0.6                       (Yogurt, Kidney Beans)       2
17      0.4                               (Milk, Yogurt)       2
18      0.4                              (Onion, Nutmeg)       2
19      0.4                             (Yogurt, Nutmeg)       2
20      0.4                              (Yogurt, Onion)       2
21      0.4                   (Eggs, Milk, Kidney Beans)       3
22      0.4                 (Eggs, Nutmeg, Kidney Beans)       3
23      0.6                  (Eggs, Onion, Kidney Beans)       3
24      0.4                 (Eggs, Yogurt, Kidney Beans)       3
25      0.4                        (Eggs, Onion, Nutmeg)       3
26      0.4                       (Eggs, Yogurt, Nutmeg)       3
27      0.4                        (Eggs, Yogurt, Onion)       3
28      0.4                 (Milk, Yogurt, Kidney Beans)       3
29      0.4                (Onion, Nutmeg, Kidney Beans)       3
30      0.4               (Yogurt, Nutmeg, Kidney Beans)       3
31      0.4                (Yogurt, Onion, Kidney Beans)       3
32      0.4                      (Yogurt, Onion, Nutmeg)       3
33      0.4          (Eggs, Onion, Nutmeg, Kidney Beans)       4
34      0.4         (Eggs, Yogurt, Nutmeg, Kidney Beans)       4
35      0.4          (Eggs, Yogurt, Onion, Kidney Beans)       4
36      0.4                (Eggs, Yogurt, Onion, Nutmeg)       4
37      0.4        (Yogurt, Onion, Nutmeg, Kidney Beans)       4
38      0.4  (Onion, Kidney Beans, Yogurt, Eggs, Nutmeg)       5

In [ ]:
#frequent_itemsets[ (frequent_itemsets['length'] == 2) &
#                   (frequent_itemsets['support'] >= 0.5) ]

In [15]:
rules = association_rules(frequent_itemsets,  min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Corn),(Kidney Beans),0.4,1.0,0.4,1.0,1.00,0.00,inf
1,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.0,1.00,0.00,inf
2,(Nutmeg),(Eggs),0.4,0.8,0.4,1.0,1.25,0.08,inf
3,(Onion),(Eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf
4,(Milk),(Kidney Beans),0.6,1.0,0.6,1.0,1.00,0.00,inf

In [16]:
rules[ (rules['lift'] >= 2.5) &
       (rules['confidence'] >= 0.8) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
21,"(Eggs, Yogurt)",(Nutmeg),0.4,0.4,0.4,1.0,2.5,0.24,inf
24,(Nutmeg),"(Eggs, Yogurt)",0.4,0.4,0.4,1.0,2.5,0.24,inf
35,"(Yogurt, Onion)",(Nutmeg),0.4,0.4,0.4,1.0,2.5,0.24,inf
38,(Nutmeg),"(Yogurt, Onion)",0.4,0.4,0.4,1.0,2.5,0.24,inf
47,"(Eggs, Yogurt, Kidney Beans)",(Nutmeg),0.4,0.4,0.4,1.0,2.5,0.24,inf
50,"(Eggs, Yogurt)","(Kidney Beans, Nutmeg)",0.4,0.4,0.4,1.0,2.5,0.24,inf
53,"(Kidney Beans, Nutmeg)","(Eggs, Yogurt)",0.4,0.4,0.4,1.0,2.5,0.24,inf
54,(Nutmeg),"(Eggs, Yogurt, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf
60,"(Eggs, Yogurt, Onion)",(Nutmeg),0.4,0.4,0.4,1.0,2.5,0.24,inf
64,"(Eggs, Yogurt)","(Onion, Nutmeg)",0.4,0.4,0.4,1.0,2.5,0.24,inf
65,"(Eggs, Nutmeg)","(Yogurt, Onion)",0.4,0.4,0.4,1.0,2.5,0.24,inf
66,"(Yogurt, Onion)","(Eggs, Nutmeg)",0.4,0.4,0.4,1.0,2.5,0.24,inf
68,"(Onion, Nutmeg)","(Eggs, Yogurt)",0.4,0.4,0.4,1.0,2.5,0.24,inf
69,(Nutmeg),"(Eggs, Yogurt, Onion)",0.4,0.4,0.4,1.0,2.5,0.24,inf
71,"(Yogurt, Onion, Kidney Beans)",(Nutmeg),0.4,0.4,0.4,1.0,2.5,0.24,inf
74,"(Yogurt, Onion)","(Kidney Beans, Nutmeg)",0.4,0.4,0.4,1.0,2.5,0.24,inf
77,"(Kidney Beans, Nutmeg)","(Yogurt, Onion)",0.4,0.4,0.4,1.0,2.5,0.24,inf
78,(Nutmeg),"(Yogurt, Onion, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf
79,"(Eggs, Yogurt, Onion, Kidney Beans)",(Nutmeg),0.4,0.4,0.4,1.0,2.5,0.24,inf
84,"(Yogurt, Onion, Kidney Beans)","(Eggs, Nutmeg)",0.4,0.4,0.4,1.0,2.5,0.24,inf
85,"(Onion, Nutmeg, Kidney Beans)","(Eggs, Yogurt)",0.4,0.4,0.4,1.0,2.5,0.24,inf
86,"(Eggs, Yogurt, Onion)","(Nutmeg, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf
89,"(Eggs, Yogurt, Kidney Beans)","(Onion, Nutmeg)",0.4,0.4,0.4,1.0,2.5,0.24,inf
91,"(Eggs, Nutmeg, Kidney Beans)","(Yogurt, Onion)",0.4,0.4,0.4,1.0,2.5,0.24,inf
93,"(Yogurt, Onion)","(Eggs, Nutmeg, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf
94,"(Onion, Nutmeg)","(Eggs, Yogurt, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf
95,"(Nutmeg, Kidney Beans)","(Eggs, Yogurt, Onion)",0.4,0.4,0.4,1.0,2.5,0.24,inf
96,"(Eggs, Yogurt)","(Onion, Nutmeg, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf
98,"(Eggs, Nutmeg)","(Yogurt, Onion, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf
99,(Nutmeg),"(Eggs, Yogurt, Onion, Kidney Beans)",0.4,0.4,0.4,1.0,2.5,0.24,inf